# Generated by Django 5.1.2 on 2024-12-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Education_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=255, verbose_name='Код')),
                ('year_of_conclude', models.IntegerField(verbose_name='Год завершения')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='Form_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(max_length=255, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Форма контроля',
                'verbose_name_plural': 'Формы контроля',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название группы')),
                ('code', models.TextField(max_length=255, verbose_name='Код группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Practise_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название типа практики')),
            ],
            options={
                'verbose_name': 'Тип практики',
                'verbose_name_plural': 'Типы практики',
            },
        ),
        migrations.CreateModel(
            name='Rating_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип рейтинга',
                'verbose_name_plural': 'Типы рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=255, verbose_name='Код')),
                ('title', models.TextField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='administrator_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='administrator_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.form_control')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.group')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.teacher')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузки',
            },
        ),
        migrations.CreateModel(
            name='Hours_per_semestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Часы')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('disciple', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.disciple')),
                ('education_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.education_plan')),
            ],
            options={
                'verbose_name': 'Часы за семестр',
                'verbose_name_plural': 'Часы за семестр',
            },
        ),
        migrations.AddField(
            model_name='form_control',
            name='hps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.hours_per_semestr'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=255, verbose_name='Мероприятие')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('rating_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.rating_type')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол')),
                ('school', models.TextField(max_length=255, verbose_name='Школа')),
                ('entery_score', models.IntegerField(verbose_name='Средний балл')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.group')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.rating')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Practise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('education_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.education_plan')),
                ('practise_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.practise_type')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.student')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('form_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.form_control')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.student')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Course_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('hps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.hours_per_semestr')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.student')),
            ],
            options={
                'verbose_name': 'Курсовая работа/проект',
                'verbose_name_plural': 'Курсовые работы/проекты',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.complexity')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.student')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемости',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('education_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.education_plan')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.teacher')),
            ],
            options={
                'verbose_name': 'Диплом?',
                'verbose_name_plural': 'Дипломы?',
            },
        ),
    ]
