# Generated by Django 5.0.13 on 2025-03-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academ",
            fields=[
                (
                    "academ_id",
                    models.AutoField(
                        db_column="Academ_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID академотпуска",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_column="Start_date", verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_column="End_date",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Академический отпуск",
                "verbose_name_plural": "Академические отпуска",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "att_id",
                    models.AutoField(
                        db_column="ATT_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID посещаемости",
                    ),
                ),
                (
                    "percent_of_attendance",
                    models.FloatField(
                        blank=True,
                        db_column="Percent_of_attendance",
                        null=True,
                        verbose_name="Процент посещаемости",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещаемость",
                "verbose_name_plural": "Посещаемость",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourseProjects",
            fields=[
                (
                    "course_id",
                    models.AutoField(
                        db_column="Course_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID курсового проекта",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True, db_column="Grade", null=True, verbose_name="Оценка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курсовой проект",
                "verbose_name_plural": "Курсовые проекты",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DebtAudit",
            fields=[
                (
                    "audit_id",
                    models.AutoField(
                        db_column="Audit_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID аудита",
                    ),
                ),
                ("date", models.DateField(db_column="Date", verbose_name="Дата")),
                (
                    "debt_event",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Debt_Event",
                        max_length=20,
                        null=True,
                        verbose_name="Событие задолженности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит задолженности",
                "verbose_name_plural": "Аудиты задолженностей",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "debt_id",
                    models.AutoField(
                        db_column="Debt_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID задолженности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задолженность",
                "verbose_name_plural": "Задолженности",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "diploma_id",
                    models.AutoField(
                        db_column="Diploma_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID диплома",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True, db_column="Grade", null=True, verbose_name="Оценка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Диплом",
                "verbose_name_plural": "Дипломы",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Disciples",
            fields=[
                (
                    "disciple_id",
                    models.AutoField(
                        db_column="Disciple_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID дисциплины",
                    ),
                ),
                (
                    "disciple_name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Disciple_name",
                        max_length=255,
                        null=True,
                        verbose_name="Название дисциплины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EducationPlan",
            fields=[
                (
                    "plan_id",
                    models.AutoField(
                        db_column="Plan_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID плана",
                    ),
                ),
                (
                    "year_of_conclude",
                    models.IntegerField(
                        blank=True,
                        db_column="Year_of_conclude",
                        null=True,
                        verbose_name="Год утверждения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план",
                "verbose_name_plural": "Учебные планы",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FormControl",
            fields=[
                (
                    "fc_id",
                    models.AutoField(
                        db_column="FC_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID формы контроля",
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Form",
                        max_length=255,
                        null=True,
                        verbose_name="Форма контроля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма контроля",
                "verbose_name_plural": "Формы контроля",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grades",
            fields=[
                (
                    "grade_id",
                    models.AutoField(
                        db_column="Grade_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID оценки",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Grade",
                        max_length=20,
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "group_id",
                    models.AutoField(
                        db_column="Group_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID группы",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Title",
                        max_length=255,
                        null=True,
                        verbose_name="Название группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HoursPerSemest",
            fields=[
                (
                    "hps_id",
                    models.AutoField(
                        db_column="HPS_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID часов в семестр",
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(
                        blank=True,
                        db_column="Hours",
                        null=True,
                        verbose_name="Количество часов",
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        blank=True,
                        db_column="Semester",
                        null=True,
                        verbose_name="Семестр",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        db_column="Start_date",
                        null=True,
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_column="End_date",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часы в семестр",
                "verbose_name_plural": "Часы в семестр",
                "db_table": "Hours_per_semest",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nagruzka",
            fields=[
                (
                    "nagruzka_id",
                    models.AutoField(
                        db_column="Nagruzka_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID нагрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нагрузка",
                "verbose_name_plural": "Нагрузки",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Practise",
            fields=[
                (
                    "practise_id",
                    models.AutoField(
                        db_column="Practise_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID практики",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True, db_column="Grade", null=True, verbose_name="Оценка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Практика",
                "verbose_name_plural": "Практики",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PractiseType",
            fields=[
                (
                    "type_id",
                    models.AutoField(
                        db_column="Type_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID типа практики",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Title",
                        max_length=255,
                        null=True,
                        verbose_name="Название типа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип практики",
                "verbose_name_plural": "Типы практик",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "rating_id",
                    models.AutoField(
                        db_column="Rating_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID рейтинга",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Event",
                        max_length=255,
                        null=True,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, db_column="Score", null=True, verbose_name="Баллы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
                "db_table": "Rating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RatingType",
            fields=[
                (
                    "type_id",
                    models.AutoField(
                        db_column="Type_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID типа рейтинга",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Title",
                        max_length=255,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип рейтинга",
                "verbose_name_plural": "Типы рейтинга",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Code",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Код",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Title",
                        max_length=255,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.AutoField(
                        db_column="Student_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID студента",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Name",
                        max_length=255,
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        db_column="Birth_date",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Sex",
                        max_length=255,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "entry_score",
                    models.IntegerField(
                        blank=True,
                        db_column="Entry_score",
                        null=True,
                        verbose_name="Баллы при поступлении",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="School",
                        max_length=255,
                        null=True,
                        verbose_name="Школа",
                    ),
                ),
                (
                    "debt",
                    models.BooleanField(
                        blank=True,
                        db_column="Debt",
                        null=True,
                        verbose_name="Долг по предметам",
                    ),
                ),
                (
                    "middle_value_of_sertificate",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Middle_value_of_sertificate",
                        max_length=255,
                        null=True,
                        verbose_name="Средний балл аттестата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "teacher_id",
                    models.AutoField(
                        db_column="Teacher_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID преподавателя",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Teacher_name",
                        max_length=255,
                        null=True,
                        verbose_name="ФИО преподавателя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="administrator_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="administrator_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
            },
        ),
    ]
