# Generated by Django 5.1.2 on 2024-12-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nagruzka',
            new_name='Complexity',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='nagruzka',
            new_name='complexity',
        ),
    ]
