# Generated by Django 5.1.2 on 2024-10-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_group_alter_student_options_alter_student_fio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
    ]
