# Generated by Django 5.1.2 on 2024-12-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_course_project_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours_per_semestr',
            old_name='plan',
            new_name='education_plan',
        ),
    ]
